.DEFAULT_GOAL := compile

.PHONY:compile

compile:
	cp ./Array.jack test/ArrayTest
	./tools/JackCompiler.sh ./test/ArrayTest
	cp ./Keyboard.jack test/KeyboardTest
	./tools/JackCompiler.sh ./test/KeyboardTest
	cp ./Math.jack test/MathTest
	./tools/JackCompiler.sh ./test/MathTest
	cp ./Memory.jack test/MemoryTest
	./tools/JackCompiler.sh ./test/MemoryTest
	cp ./Output.jack test/OutputTest
	./tools/JackCompiler.sh ./test/OutputTest
	cp ./Screen.jack test/ScreenTest
	./tools/JackCompiler.sh ./test/ScreenTest
	cp ./String.jack test/StringTest
	./tools/JackCompiler.sh ./test/StringTest
	cp ./Sys.jack test/SysTest
	./tools/JackCompiler.sh ./test/SysTest
